apiVersion: v1
kind: ConfigMap
metadata:
  name: games-config
  namespace: services
data:
  Jwt__Issuer: 'Tapir Chess'
  Jwt__Audience: 'https://tapirchess.dev'
  EventStore__Servers__0__Host: 'mongodb-games-headless.mongodb.svc.cluster.local'
  EventStore__Servers__0__Port: '27017'
  EventStore__DatabaseName: 'games'
  EventStore__AuthenticationMethod: 'SCRAM-SHA-256'
  EventStore__Username: 'games'
  MessageBus__Host: 'rabbitmq-headless.rabbitmq.svc.cluster.local'
  MessageBus__Port: '5672'
  MessageBus__Username: 'games'
  MessageBus__QueueName: 'games'