apiVersion: v1
kind: ConfigMap
metadata:
  name: players-config
  namespace: services
data:
  Jwt__Issuer: 'Tapir Chess'
  Jwt__Audience: 'https://tapirchess.dev'
  EventStore__Servers__0__Host: 'mongodb-players-headless.mongodb.svc.cluster.local'
  EventStore__Servers__0__Port: '27017'
  EventStore__DatabaseName: 'players'
  EventStore__AuthenticationMethod: 'SCRAM-SHA-256'
  EventStore__Username: 'players'
  MessageBus__Host: 'rabbitmq-headless.rabbitmq.svc.cluster.local'
  MessageBus__Port: '5672'
  MessageBus__Username: 'players'
  MessageBus__QueueName: 'players'
  Serilog__Using__0: 'Serilog.Sinks.Grafana.Loki'
  Serilog__MinimumLevel__Default: 'Debug'
  Serilog__WriteTo__0__Name: 'Console'
  Serilog__WriteTo__1__Name: 'GrafanaLoki'
  Serilog__WriteTo__1__Args__uri: 'http://loki-gateway.loki.svc.cluster.local:80'
  Serilog__WriteTo__1__Args__labels__0__key: 'service_name'
  Serilog__WriteTo__1__Args__labels__0__value: 'players'