apiVersion: v1
kind: ConfigMap
metadata:
  name: news-config
data:
  Jwt__Issuer: 'Tapir Chess'
  Jwt__Audience: 'https://tapirchess.dev'
  EventStore__Servers__0__Host: 'mongodb-0.mongodb-headless.infrastructure.svc.cluster.local'
  EventStore__Servers__0__Port: '27017'
  EventStore__DatabaseName: 'news'
  EventStore__AuthenticationMethod: 'SCRAM-SHA-256'
  EventStore__Username: 'news'
  MessageBus__Host: 'rabbitmq-0.rabbitmq-headless.infrastructure.svc.cluster.local'
  MessageBus__Port: '5672'
  MessageBus__Username: 'news'
  MessageBus__QueueName: 'news'