version: '3.4'

services:
  tapir-services-news:
    image: ${DOCKER_REGISTRY-}tapirservicesnews
    build:
      context: .
      dockerfile: src/Tapir.Services.News.API/Dockerfile

  mongodb:
    image: mongo:latest
    hostname: mongodb