services:
  tapir-gateway:
    image: ${DOCKER_REGISTRY-}tapirgateway
    build:
      context: .
      dockerfile: src/Tapir.Gateway/Dockerfile

  tapir-services-news:
    image: ${DOCKER_REGISTRY-}tapirservicesnews
    hostname: tapir-services-news
    build:
      context: .
      dockerfile: src/Tapir.Services.News.API/Dockerfile

  postgresql:
    image: postgres:latest
    hostname: postgresql

  mongodb:
    image: mongo:latest
    hostname: mongodb
