services:
  tapir-gateway:
    image: ${DOCKER_REGISTRY-}tapirgateway
    hostname: tapir-gateway
    build:
      context: .
      dockerfile: src/Tapir.Gateway/Dockerfile

  tapir-identity:
    image: ${DOCKER_REGISTRY-}tapiridentity
    hostname: tapir-identity
    build:
      context: .
      dockerfile: src/Tapir.Identity.API/Dockerfile

  tapir-services-news:
    image: ${DOCKER_REGISTRY-}tapirservicesnews
    hostname: tapir-services-news
    build:
      context: .
      dockerfile: src/Tapir.Services.News.API/Dockerfile
      
  tapir-services-players:
    image: ${DOCKER_REGISTRY-}tapirservicesplayers
    hostname: tapir-services-players
    build:
      context: .
      dockerfile: src/Tapir.Services.Players.API/Dockerfile

  tapir-services-games:
    image: ${DOCKER_REGISTRY-}tapirservicesgames
    hostname: tapir-services-games
    build:
      context: .
      dockerfile: src/Tapir.Services.Games.API/Dockerfile

  postgresql:
    image: postgres:17.5
    hostname: postgresql

  mongodb:
    image: mongo:8.0.10-noble
    hostname: mongodb

  mailpit:
    image: axllent/mailpit:v1.26
    hostname: mailpit

  rabbitmq:
    image: rabbitmq:4.1.1-management
    hostname: rabbitmq