services:
  tapir-gateway:
    image: ${DOCKER_REGISTRY-}tapirgateway
    hostname: tapir-gateway
    build:
      context: .
      dockerfile: src/Tapir.Gateway/Dockerfile

  tapir-identity:
    image: ${DOCKER_REGISTRY-}tapiridentity
    hostname: tapir-identity
    build:
      context: .
      dockerfile: src/Tapir.Identity.API/Dockerfile

  tapir-services-news:
    image: ${DOCKER_REGISTRY-}tapirservicesnews
    hostname: tapir-services-news
    build:
      context: .
      dockerfile: src/Tapir.Services.News.API/Dockerfile
      
  tapir-services-players:
    image: ${DOCKER_REGISTRY-}tapirservicesplayers
    hostname: tapir-services-players
    build:
      context: .
      dockerfile: src/Tapir.Services.Players.API/Dockerfile

  postgresql:
    image: postgres:latest
    hostname: postgresql

  mongodb:
    image: mongo:latest
    hostname: mongodb

  mailpit:
    image: axllent/mailpit:latest
    hostname: mailpit