deploymentMode: SingleBinary
loki:
  commonConfig:
    replication_factor: 1
  auth_enabled: false
  storage:
    type: s3
    bucketNames:
      chunks: "chunks"
      ruler: "ruler"
      admin: "admin"
    s3:
      s3: http://192.168.100.80:9000
      endpoint: http://192.168.100.80:9000
      accessKeyId: "${LOKI_S3_ACCESSKEYID}"
      secretAccessKey: "${LOKI_S3_SECRETACCESSKEY}"
      s3ForcePathStyle: true
      insecure: true
  schemaConfig:
    configs:
      - from: 2024-04-01
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  ingester:
    chunk_encoding: snappy
backend:
  extraArgs:
    - '-config.expand-env=true'
  extraEnvFrom: 
    - secretRef:
      name: loki-secret
read:
  extraArgs:
    - '-config.expand-env=true'
  extraEnvFrom: 
    - secretRef:
      name: loki-secret
write:
  extraArgs:
    - '-config.expand-env=true'
  extraEnvFrom: 
    - secretRef:
      name: loki-secret
singleBinary:
  extraArgs:
    - '-config.expand-env=true'
  extraEnvFrom: 
    - secretRef:
        name: loki-secret