auth:
  username: tapir
  existingPasswordSecret: rabbitmq-secret
initScriptsSecret: rabbitmq-init
replicaCount: 2
nodeSelector:
  type: rabbitmq
podAntiAffinityPreset: hard
persistence:
  size: 1Gi
resources:
  requests:
    cpu: 1
    memory: 256Mi
  limits:
    cpu: 2
    memory: 512Mi