apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql-players-cluster
  namespace: postgresql
spec:
  instances: 2
  enableSuperuserAccess: true
  superuserSecret:
    name: postgresql-players-postgres-secret
  bootstrap:
    initdb:
      database: players
      owner: players
      secret:
        name: postgresql-players-user-secret
  primaryUpdateStrategy: unsupervised
  affinity:
    nodeSelector:
      type: database-players
    podAntiAffinityType: required
  storage:
    size: 1Gi
  resources:
    requests:
      cpu: 1
      memory: 256Mi
    limits:
      cpu: 2
      memory: 512Mi
  monitoring:
    enablePodMonitor: true