apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql-news-cluster
  namespace: postgresql
spec:
  instances: 2
  enableSuperuserAccess: true
  superuserSecret:
    name: postgresql-news-postgres-secret
  bootstrap:
    initdb:
      database: news
      owner: news
      secret:
        name: postgresql-news-user-secret
  primaryUpdateStrategy: unsupervised
  affinity:
    nodeSelector:
      type: database-news
    podAntiAffinityType: required
  storage:
    size: 1Gi
  resources:
    requests:
      cpu: 1
      memory: 256Mi
    limits:
      cpu: 2
      memory: 512Mi
  monitoring:
    enablePodMonitor: true