apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql-games-cluster
  namespace: postgresql
spec:
  instances: 2
  enableSuperuserAccess: true
  superuserSecret:
    name: postgresql-games-postgres-secret
  bootstrap:
    initdb:
      database: games
      owner: games
      secret:
        name: postgresql-games-user-secret
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi