apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql-identity-cluster
  namespace: postgresql
spec:
  instances: 2
  enableSuperuserAccess: true
  superuserSecret:
    name: postgresql-identity-postgres-secret
  bootstrap:
    initdb:
      database: identity
      owner: identity
      secret:
        name: postgresql-identity-user-secret
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi