@HostAddress = http://localhost:9000

POST {{HostAddress}}/api/auth/login
Accept: application/json
Content-Type: application/json
{
    "Username": "tapir2",
    "Password": "Tapir123!@#"
}

###

POST {{HostAddress}}/api/auth/register
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyZDg4Y2M5Yy0wMGMyLTQ0MDEtYWYxOC01NTEwYjAwMjFiNjkiLCJlbWFpbCI6InRlc3RAdGVzdC5wbCIsImp0aSI6ImI1NjM3Zjc0LWQ1OTctNDM3Mi1iMzRkLTY3YjZmYWQ3YThlZiIsImV4cCI6MTc0MjU4NzQ0NCwiaXNzIjoiVGFwaXIgQ2hlc3MiLCJhdWQiOiJodHRwczovL3RhcGlyY2hlc3MuZGV2In0.E-_fXlQqUF2gRK2QJ8xHBmnhX-Mt-8XcDAGi7mYIAKo
Accept: application/json
Content-Type: application/json
{
    "Username": "tapir2",
    "Email": "tapir2@test.test",
    "Password": "Tapir123!@#"
}

###

POST {{HostAddress}}/api/auth/register/confirm
Accept: application/json
Content-Type: application/json
{
    "UserId": "tapir2",
    "Token": "aaaaaaaaaaaaaaaabbbbbbbbbbbbbcccccccccccccc"
}

###

POST {{HostAddress}}/api/auth/refresh-token
Accept: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1MTVmNWFlMi0yOTExLTQwNWUtYWNiYi1hNjEyNTUwMjNhOTEiLCJuYW1lIjoidGVzdCIsImVtYWlsIjoidGVzdEB0ZXN0LnBsIiwianRpIjoiZDBlMGZjYWItYTFkYS00MWMzLWEzNGMtYzA0YzZiOTljNDQxIiwiZXhwIjoxNzQyNjQ2MDM2LCJpc3MiOiJUYXBpciBDaGVzcyIsImF1ZCI6Imh0dHBzOi8vdGFwaXJjaGVzcy5kZXYifQ.Dyk5xXOlabrbvrRN_oa3BpBuREek81KwZws8_I-uffI
Content-Type: application/json
{
    "RefreshToken": "k+CYh2ag2EBlU3cOzqCy34G3u9a67DD7JzOPnZ+VeqGCzeOBi7+4K7oIWgwHcOJQr57L97TVHBnLQCdYP6i3J5ySAhM2OeQ0Qe0kANm68kUkPx3qVjnDOaRFY/jawQz4h8OPGSCQRbOS/cZ1agXrnJ2C2yqUjLLhi5hHaaR8RFM="
}

###

POST {{HostAddress}}/api/auth/reset-password
Accept: application/json
Content-Type: application/json
{
    "Email": "test1g232@test.pl"
}

###

POST {{HostAddress}}/api/auth/reset-password/confirm
Accept: application/json
Content-Type: application/json
{
    "UserId": "YmJkZjA2ODUtZmYyMi00YzMwLTkzYWYtNGNiMTgwYjM0ZjIz",
    "Token": "Q2ZESjhCVjJpUmNXUmlwTGpJakJrZFBJR1V6TW12UDFlMVRXZXN4ZGk4cnRCbHFEdjdUczUxMkcvWHhnYlluZklFNmVzVWJRaG8vL3pmL3hNclhFWXBEb1lKV1E3TTdWSmNLRkEvVnA5QUlsbEVsa3hFSG1IMHN5UUUvZHZDSTYwaDcyNEJ3b084VFdaUVNBMzVGeFRxdFRrbjluOVdzT1psTFhtMm1YVFY1b0lieUlIbG9mb2cyL1ZrQXYxcEZqQmNDWWs5RTk5T0Y2dXZma2xGS3hNK0IyMlJ0ckptMmw2N2szQTl3S2ZUMjI2TTJy",
    "Password": "Test123!"
}

###

POST {{HostAddress}}/api/account/change-password
Accept: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkODA1YzY0ZC02Y2VjLTRmNGYtODEwNS0wZTEzOGE0OTRlZjciLCJuYW1lIjoidGFwaXIyIiwiZW1haWwiOiJ0YXBpcjJAdGVzdC50ZXN0IiwianRpIjoiZjNjZmVmOTMtMzYxMC00MGYxLTg5MmQtYTIzZTZiNTM1MjQ3Iiwicm9sZSI6WyJhZG1pbiIsInVzZXIiXSwiZXhwIjoxNzQzMDE4NTc3LCJpc3MiOiJUYXBpciBDaGVzcyIsImF1ZCI6Imh0dHBzOi8vdGFwaXJjaGVzcy5kZXYifQ.NcOzVNi_Qm-o4vqSQYvpiTYFI5zk8WrtJKuaXHTdTFg; path=/; secure; samesite=strict; httponly, refresh_token=5lx4PljlFI1FNt3ePodJOrbXsPVvK62hRTxNw4SB%2BW%2BtZQ9ABUKTNkVv5u8QPWQ9Tqy5fYagx4mde7mBmJH2GnYC7Ivjgn8F69fVDJg2TzWXfpKBMJnHikOwskJfk8Pmo7bi8FJSc45JLSJkCMoi5c%2BlSz6HxD8%2BHWMz3wz7KMk%3D; path=/api/auth/refresh-token; secure; samesite=strict; httponly
Content-Type: application/json
{
    "OldPassword": "",
    "NewPassword": "Asd123!"
}

###