@HostAddress = https://localhost:9000

POST {{HostAddress}}/api/auth/signin
Accept: application/json
Content-Type: application/json
{
    "Username": "admin",
    "Password": "Admin123!",
    "RememberMe": true
}

###

POST {{HostAddress}}/api/auth/signout
Accept: application/json
Content-Type: application/json
{

}

###

POST {{HostAddress}}/api/auth/register
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyZDg4Y2M5Yy0wMGMyLTQ0MDEtYWYxOC01NTEwYjAwMjFiNjkiLCJlbWFpbCI6InRlc3RAdGVzdC5wbCIsImp0aSI6ImI1NjM3Zjc0LWQ1OTctNDM3Mi1iMzRkLTY3YjZmYWQ3YThlZiIsImV4cCI6MTc0MjU4NzQ0NCwiaXNzIjoiVGFwaXIgQ2hlc3MiLCJhdWQiOiJodHRwczovL3RhcGlyY2hlc3MuZGV2In0.E-_fXlQqUF2gRK2QJ8xHBmnhX-Mt-8XcDAGi7mYIAKo
Accept: application/json
Content-Type: application/json
{
    "Username": "tapir2",
    "Email": "tapir2@test.test",
    "Password": "Tapir123!@#"
}

###

POST {{HostAddress}}/api/auth/register/confirm
Accept: application/json
Content-Type: application/json
{
    "UserId": "tapir2",
    "Token": "aaaaaaaaaaaaaaaabbbbbbbbbbbbbcccccccccccccc"
}

###

POST {{HostAddress}}/api/auth/refresh-token
Accept: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzOWVkNWE3Ny00ZmVhLTRlM2QtODI2NS0yZDY5YWI3Y2IyOTYiLCJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGxvY2FsaG9zdCIsImp0aSI6IjE5ZmQ3OGNlLTJjNmMtNDY4YS05ZjNhLTIyMmY5MjVjOTAyMSIsInJvbGUiOlsiYWRtaW4iLCJ1c2VyIl0sImV4cCI6MTc0NDc1NTcxMSwiaXNzIjoiVGFwaXIgQ2hlc3MiLCJhdWQiOiJodHRwczovL3RhcGlyY2hlc3MuZGV2In0.lBHz4h4AkWw2GONCYw82rR4ruQj3uMpjZbhXQP7pKSw; max-age=900; path=/; secure; samesite=strict; httponly, refresh_token=KTAOY%2FJ%2F1XG40h0aTgrvYcOyeFujvzajWV4sqB8zKDu9%2B8KiIC1vLREI%2BATms9VUWkpIxIJx7zQOCtEu%2BGd37GlwJVEIW1CFcM%2BCC3Qe3rsJiBnPpQ%2FyO%2FAdpAunS%2FFXIjUulKbDWGYHiRIrkeLt1xKDJcU3L%2FfL19zYhhAmZE0%3D; max-age=15552000; path=/api/auth/refresh-token; secure; samesite=strict; httponly, remember_me=true; max-age=15552000; path=/; secure; samesite=strict; httponly

###

POST {{HostAddress}}/api/auth/reset-password
Accept: application/json
Content-Type: application/json
{
    "Email": "test1g232@test.pl"
}

###

POST {{HostAddress}}/api/auth/reset-password/confirm
Accept: application/json
Content-Type: application/json
{
    "UserId": "YmJkZjA2ODUtZmYyMi00YzMwLTkzYWYtNGNiMTgwYjM0ZjIz",
    "Token": "Q2ZESjhCVjJpUmNXUmlwTGpJakJrZFBJR1V6TW12UDFlMVRXZXN4ZGk4cnRCbHFEdjdUczUxMkcvWHhnYlluZklFNmVzVWJRaG8vL3pmL3hNclhFWXBEb1lKV1E3TTdWSmNLRkEvVnA5QUlsbEVsa3hFSG1IMHN5UUUvZHZDSTYwaDcyNEJ3b084VFdaUVNBMzVGeFRxdFRrbjluOVdzT1psTFhtMm1YVFY1b0lieUlIbG9mb2cyL1ZrQXYxcEZqQmNDWWs5RTk5T0Y2dXZma2xGS3hNK0IyMlJ0ckptMmw2N2szQTl3S2ZUMjI2TTJy",
    "Password": "Test123!"
}

###

POST {{HostAddress}}/api/account/change-username
Accept: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYWUzZTY1OS0wMTAyLTRjMDAtYWQxNC02YTM2OGFhZjU5ZWUiLCJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGxvY2FsaG9zdCIsImp0aSI6IjkxOThmNjA0LTk5ZGQtNGJmNC1hOWVjLTA3YjliNTNhYTEzYiIsInJvbGUiOlsiYWRtaW4iLCJ1c2VyIl0sImV4cCI6MTc0NTE1NzQ1OSwiaXNzIjoiVGFwaXIgQ2hlc3MiLCJhdWQiOiJodHRwczovL3RhcGlyY2hlc3MuZGV2In0.79joFMUX3bdgIAnMce8Yk5hKBi6aNMUZ11NrdeK97eQ; path=/; secure; samesite=none; httponly, refresh_token=MQc1SVwy7eT7rzxV%2B4RDOBrI9NKR32EXgkK8CeRuO%2FabbeQJGw9MOpdXEHgiyxrGvCLi%2BpoQtXfS%2FPw8JAWdun605sMsK%2BEn4W6xS9%2BSRGN48cSX9AuT3AH5ZG1H0Wauz4ItFVbVWZ9OFYp%2F59FgS7ovJNHFTXNzAorM8yg0ugA%3D; max-age=15552000; path=/api/auth/refresh-token; secure; samesite=none; httponly, remember_me=true; max-age=15552000; path=/; secure; samesite=none; httponly
Content-Type: application/json
{
    "Username": "test123"
}

###

POST {{HostAddress}}/api/account/change-password
Accept: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkODA1YzY0ZC02Y2VjLTRmNGYtODEwNS0wZTEzOGE0OTRlZjciLCJuYW1lIjoidGFwaXIyIiwiZW1haWwiOiJ0YXBpcjJAdGVzdC50ZXN0IiwianRpIjoiZjNjZmVmOTMtMzYxMC00MGYxLTg5MmQtYTIzZTZiNTM1MjQ3Iiwicm9sZSI6WyJhZG1pbiIsInVzZXIiXSwiZXhwIjoxNzQzMDE4NTc3LCJpc3MiOiJUYXBpciBDaGVzcyIsImF1ZCI6Imh0dHBzOi8vdGFwaXJjaGVzcy5kZXYifQ.NcOzVNi_Qm-o4vqSQYvpiTYFI5zk8WrtJKuaXHTdTFg; path=/; secure; samesite=strict; httponly, refresh_token=5lx4PljlFI1FNt3ePodJOrbXsPVvK62hRTxNw4SB%2BW%2BtZQ9ABUKTNkVv5u8QPWQ9Tqy5fYagx4mde7mBmJH2GnYC7Ivjgn8F69fVDJg2TzWXfpKBMJnHikOwskJfk8Pmo7bi8FJSc45JLSJkCMoi5c%2BlSz6HxD8%2BHWMz3wz7KMk%3D; path=/api/auth/refresh-token; secure; samesite=strict; httponly
Content-Type: application/json
{
    "OldPassword": "",
    "NewPassword": "Asd123!"
}

###

POST {{HostAddress}}/api/account/info
Accept: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzOWVkNWE3Ny00ZmVhLTRlM2QtODI2NS0yZDY5YWI3Y2IyOTYiLCJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGxvY2FsaG9zdCIsImp0aSI6ImQ4MGIyZGExLTIxZTQtNDczYS05YTNmLWM4MmRlYTdjZGE3MSIsInJvbGUiOlsiYWRtaW4iLCJ1c2VyIl0sImV4cCI6MTc0NDkxNzE5MiwiaXNzIjoiVGFwaXIgQ2hlc3MiLCJhdWQiOiJodHRwczovL3RhcGlyY2hlc3MuZGV2In0.b6TXIVzuxP7y3Ts0DVNzExy0ux1BJlHRVMUFu4XTOXA; 
Content-Type: application/json
{
    
}

###