architecture: replicaset
auth:
  rootUser: tapir
  usernames:
    - games
    - news
    - players
  databases:
    - games
    - news
    - players
  existingSecret: "mongodb-secret"
initdbScripts:
  init.js: |
    let databases = ['news', 'players', 'games'];
    databases.forEach((name) => {
      db = db.getSiblingDB(name);
      db.grantRolesToUser(name, [{
        role: "readWrite",
        db: name
      }]);
      db.events.createIndex({ "AggregateId": 1 });
      db.events.createIndex({ "Timestamp": 1 });
    });
persistence:
  size: 1Gi
replicaCount: 1