CREATE TABLE Players (
  Id UUID PRIMARY KEY NOT NULL,
  CreatedAt TIMESTAMP NOT NULL,
  UpdatedAt TIMESTAMP NULL,
  DeletedAt TIMESTAMP NULL,
  UserId UUID NOT NULL,
  Username TEXT NULL,
  Email TEXT NULL,
  Country TEXT NULL,
  AboutMe TEXT NULL
);