CREATE TABLE News (
  Id UUID PRIMARY KEY NOT NULL,
  CreatedAt TIMESTAMP NOT NULL,
  UpdatedAt TIMESTAMP NULL,
  DeletedAt TIMESTAMP NULL,
  Title TEXT NULL,
  Alias TEXT NULL,
  Content TEXT NULL,
  Deleted BOOLEAN NOT NULL DEFAULT FALSE
);