@HostAddress = http://localhost:9020

GET {{HostAddress}}/api/news?pageSize=3&pageNumber=3
Accept: application/json

###

GET {{HostAddress}}/api/news/cdd407cd-196f-43a2-ba00-9d15f0a459ec
Accept: application/json

###

POST {{HostAddress}}/api/news/
Content-Type: application/json
{
    "title": "Title",
    "alias": "alias",
    "content": "Content"
}

###

PATCH {{HostAddress}}/api/news/c0d407cd-196f-43a2-ba00-9d15f0a459ec
Content-Type: application/json
{
    "id": "c0d407cd-196f-43a2-ba00-9d15f0a459ec",
    "title": "Title",
    "alias": "alias",
    "content": "Content"
}

###

DELETE {{HostAddress}}/api/news/9c91f778-ed52-4204-84ab-68885e6f3df3