@HostAddress = http://localhost:9020

GET {{HostAddress}}/api/news?pageSize=10&pageNumber=1
Accept: application/json

###

GET {{HostAddress}}/api/news/cdd407cd-196f-43a2-ba00-9d15f0a459ec
Accept: application/json

###

POST {{HostAddress}}/api/news/
Content-Type: application/json
{
    "title": "Title",
    "alias": "alias",
    "content": "Content"
}

###

PATCH {{HostAddress}}/api/news/130c641e-fa9c-4918-9a86-542117bd4f05
Content-Type: application/json
{
    "id": "130c641e-fa9c-4918-9a86-542117bd4f05",
    "title": "Title",
    "alias": "alias",
    "content": "Content"
}

###

DELETE {{HostAddress}}/api/news/9c91f778-ed52-4204-84ab-68885e6f3df3

#############
### ADMIN ###
#############

POST {{HostAddress}}/api/admin/rebuild-read-model
Content-Type: application/json
{

}