apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql-games-cluster
  namespace: postgresql
spec:
  instances: 1
  affinity:
    nodeSelector: null
    podAntiAffinityType: null