apiVersion: apps/v1
kind: Deployment
metadata:
  name: games
  namespace: services
  labels:
    app: games
spec:
  replicas: 2
  selector:
    matchLabels:
      app: games
  template:
    metadata:
      labels:
        app: games
    spec:
      containers:
      - name: games
        image: tearthdev/tapir-services-games:build.12
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: games-config
          - secretRef:
              name: games-secret
      nodeSelector:
        type: services
      resources:
        requests:
          cpu: 1
          memory: 256Mi
        limits:
          cpu: 2
          memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: games
  namespace: services
  labels:
    app: games
spec:
  selector:
    app: games
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080