apiVersion: apps/v1
kind: Deployment
metadata:
  name: news
  namespace: services
  labels:
    app: news
spec:
  replicas: 2
  selector:
    matchLabels:
      app: news
  template:
    metadata:
      labels:
        app: news
    spec:
      containers:
      - name: news
        image: tearthdev/tapir-services-news:build.8
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: news-config
          - secretRef:
              name: news-secret
      nodeSelector:
        type: services
      resources:
        requests:
          cpu: 1
          memory: 256Mi
        limits:
          cpu: 2
          memory: 512Mi

---

apiVersion: v1
kind: Service
metadata:
  name: news
  namespace: services
spec:
  selector:
    app: news
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080