apiVersion: apps/v1
kind: Deployment
metadata:
  name: players
  namespace: services
  labels:
    app: players
spec:
  replicas: 2
  selector:
    matchLabels:
      app: players
  template:
    metadata:
      labels:
        app: players
    spec:
      containers:
      - name: players
        image: tearthdev/tapir-services-players:build.8
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: players-config
          - secretRef:
              name: players-secret
      nodeSelector:
        type: services
      resources:
        requests:
          cpu: 1
          memory: 256Mi
        limits:
          cpu: 2
          memory: 512Mi

---

apiVersion: v1
kind: Service
metadata:
  name: players
  namespace: services
spec:
  selector:
    app: players
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080