apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: services
  labels:
    app: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: tearthdev/tapir-gateway:build.2
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: gateway-config
          - secretRef:
              name: gateway-secret
      nodeSelector:
        type: services
      resources:
        requests:
          cpu: 1
          memory: 256Mi
        limits:
          cpu: 2
          memory: 512Mi

---

apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: services
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080