CREATE TABLE Rooms (
  Id UUID PRIMARY KEY NOT NULL,
  CreatedAt TIMESTAMP NOT NULL,
  UpdatedAt TIMESTAMP NULL,
  UserId UUID NOT NULL,
  Username TEXT NOT NULL,
  GameId UUID NULL,
  Time INTEGER NOT NULL DEFAULT 0,
  Increment INTEGER NOT NULL DEFAULT 0,
  Status INTEGER NOT NULL DEFAULT 0
);