CREATE TABLE Games (
  Id UUID PRIMARY KEY NOT NULL,
  CreatedAt TIMESTAMP NOT NULL,
  UpdatedAt TIMESTAMP NULL,
  UserIdWhite UUID NOT NULL,
  UserIdBlack UUID NOT NULL,
  UsernameWhite TEXT NOT NULL,
  UsernameBlack TEXT NOT NULL,
  Time INTEGER NOT NULL DEFAULT 0,
  Increment INTEGER NOT NULL DEFAULT 0,
  TimeWhite INTEGER NOT NULL DEFAULT 0,
  TimeBlack INTEGER NOT NULL DEFAULT 0,
  Pgn TEXT NULL,
  SideToMove INTEGER NOT NULL DEFAULT 0,
  Result INTEGER NOT NULL DEFAULT 0,
  Status INTEGER NOT NULL DEFAULT 0
);