on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  SOLUTION: Tapir.sln
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore $SOLUTION
    - name: Build
      run: dotnet build $SOLUTION --no-restore
    - name: Test
      run: dotnet test $SOLUTION --no-build --verbosity normal
